// Auto-generated by gen_wgmma_zoo.py — do not edit by hand.
//
// Cutlass-free Hopper wgmma multi-config harness. One kernel per config; each
// runs all-ones inputs and verifies every output equals K (layout-agnostic
// correctness gate). Wall-clock per config is captured for relative latency.
//
// Build (cutlass-free):
//   nvcc -std=c++17 -O3 -gencode=arch=compute_90a,code=sm_90a -lineinfo \
//        wgmma_zoo.cu -o wgmma_zoo

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <vector>
#include <algorithm>
#include <cuda_runtime.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>

#define CUDA_CHECK(x) do { cudaError_t err = (x); if (err != cudaSuccess) { \
    fprintf(stderr, "CUDA error %s at %s:%d\n", cudaGetErrorString(err), __FILE__, __LINE__); \
    std::exit(1); } } while (0)

__device__ __forceinline__ uint64_t make_smem_desc(
    const void* smem_ptr,
    uint32_t leading_dim_bytes,
    uint32_t stride_dim_bytes,
    uint32_t swizzle_mode = 0)
{
    uint32_t smem_int = static_cast<uint32_t>(__cvta_generic_to_shared(smem_ptr));
    uint64_t desc = 0;
    desc |= ((uint64_t)(smem_int >> 4)) & 0x3FFF;
    desc |= ((uint64_t)(leading_dim_bytes >> 4) & 0xFFFF) << 14;
    desc |= ((uint64_t)(stride_dim_bytes  >> 4) & 0xFFFF) << 30;
    desc |= ((uint64_t)(swizzle_mode & 0x3)) << 62;
    return desc;
}

__global__ void wgmma_kernel_ss_tn_bf16_n8(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 8;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n8k16.f32.bf16.bf16 {%0,%1,%2,%3}, %4, %5, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 4 + 0] = d0;
    D[tid * 4 + 1] = d1;
    D[tid * 4 + 2] = d2;
    D[tid * 4 + 3] = d3;
}

__global__ void wgmma_kernel_ss_tn_bf16_n16(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 16;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n16k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7}, %8, %9, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 8 + 0] = d0;
    D[tid * 8 + 1] = d1;
    D[tid * 8 + 2] = d2;
    D[tid * 8 + 3] = d3;
    D[tid * 8 + 4] = d4;
    D[tid * 8 + 5] = d5;
    D[tid * 8 + 6] = d6;
    D[tid * 8 + 7] = d7;
}

__global__ void wgmma_kernel_ss_tn_bf16_n32(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 32;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n32k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, %16, %17, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 16 + 0] = d0;
    D[tid * 16 + 1] = d1;
    D[tid * 16 + 2] = d2;
    D[tid * 16 + 3] = d3;
    D[tid * 16 + 4] = d4;
    D[tid * 16 + 5] = d5;
    D[tid * 16 + 6] = d6;
    D[tid * 16 + 7] = d7;
    D[tid * 16 + 8] = d8;
    D[tid * 16 + 9] = d9;
    D[tid * 16 + 10] = d10;
    D[tid * 16 + 11] = d11;
    D[tid * 16 + 12] = d12;
    D[tid * 16 + 13] = d13;
    D[tid * 16 + 14] = d14;
    D[tid * 16 + 15] = d15;
}

__global__ void wgmma_kernel_ss_tn_bf16_n64(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, %32, %33, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

__global__ void wgmma_kernel_ss_tn_bf16_n128(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 128;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;
    float d32 = 0;
    float d33 = 0;
    float d34 = 0;
    float d35 = 0;
    float d36 = 0;
    float d37 = 0;
    float d38 = 0;
    float d39 = 0;
    float d40 = 0;
    float d41 = 0;
    float d42 = 0;
    float d43 = 0;
    float d44 = 0;
    float d45 = 0;
    float d46 = 0;
    float d47 = 0;
    float d48 = 0;
    float d49 = 0;
    float d50 = 0;
    float d51 = 0;
    float d52 = 0;
    float d53 = 0;
    float d54 = 0;
    float d55 = 0;
    float d56 = 0;
    float d57 = 0;
    float d58 = 0;
    float d59 = 0;
    float d60 = 0;
    float d61 = 0;
    float d62 = 0;
    float d63 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n128k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31,%32,%33,%34,%35,%36,%37,%38,%39,%40,%41,%42,%43,%44,%45,%46,%47,%48,%49,%50,%51,%52,%53,%54,%55,%56,%57,%58,%59,%60,%61,%62,%63}, %64, %65, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31), "+f"(d32), "+f"(d33), "+f"(d34), "+f"(d35), "+f"(d36), "+f"(d37), "+f"(d38), "+f"(d39), "+f"(d40), "+f"(d41), "+f"(d42), "+f"(d43), "+f"(d44), "+f"(d45), "+f"(d46), "+f"(d47), "+f"(d48), "+f"(d49), "+f"(d50), "+f"(d51), "+f"(d52), "+f"(d53), "+f"(d54), "+f"(d55), "+f"(d56), "+f"(d57), "+f"(d58), "+f"(d59), "+f"(d60), "+f"(d61), "+f"(d62), "+f"(d63)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 64 + 0] = d0;
    D[tid * 64 + 1] = d1;
    D[tid * 64 + 2] = d2;
    D[tid * 64 + 3] = d3;
    D[tid * 64 + 4] = d4;
    D[tid * 64 + 5] = d5;
    D[tid * 64 + 6] = d6;
    D[tid * 64 + 7] = d7;
    D[tid * 64 + 8] = d8;
    D[tid * 64 + 9] = d9;
    D[tid * 64 + 10] = d10;
    D[tid * 64 + 11] = d11;
    D[tid * 64 + 12] = d12;
    D[tid * 64 + 13] = d13;
    D[tid * 64 + 14] = d14;
    D[tid * 64 + 15] = d15;
    D[tid * 64 + 16] = d16;
    D[tid * 64 + 17] = d17;
    D[tid * 64 + 18] = d18;
    D[tid * 64 + 19] = d19;
    D[tid * 64 + 20] = d20;
    D[tid * 64 + 21] = d21;
    D[tid * 64 + 22] = d22;
    D[tid * 64 + 23] = d23;
    D[tid * 64 + 24] = d24;
    D[tid * 64 + 25] = d25;
    D[tid * 64 + 26] = d26;
    D[tid * 64 + 27] = d27;
    D[tid * 64 + 28] = d28;
    D[tid * 64 + 29] = d29;
    D[tid * 64 + 30] = d30;
    D[tid * 64 + 31] = d31;
    D[tid * 64 + 32] = d32;
    D[tid * 64 + 33] = d33;
    D[tid * 64 + 34] = d34;
    D[tid * 64 + 35] = d35;
    D[tid * 64 + 36] = d36;
    D[tid * 64 + 37] = d37;
    D[tid * 64 + 38] = d38;
    D[tid * 64 + 39] = d39;
    D[tid * 64 + 40] = d40;
    D[tid * 64 + 41] = d41;
    D[tid * 64 + 42] = d42;
    D[tid * 64 + 43] = d43;
    D[tid * 64 + 44] = d44;
    D[tid * 64 + 45] = d45;
    D[tid * 64 + 46] = d46;
    D[tid * 64 + 47] = d47;
    D[tid * 64 + 48] = d48;
    D[tid * 64 + 49] = d49;
    D[tid * 64 + 50] = d50;
    D[tid * 64 + 51] = d51;
    D[tid * 64 + 52] = d52;
    D[tid * 64 + 53] = d53;
    D[tid * 64 + 54] = d54;
    D[tid * 64 + 55] = d55;
    D[tid * 64 + 56] = d56;
    D[tid * 64 + 57] = d57;
    D[tid * 64 + 58] = d58;
    D[tid * 64 + 59] = d59;
    D[tid * 64 + 60] = d60;
    D[tid * 64 + 61] = d61;
    D[tid * 64 + 62] = d62;
    D[tid * 64 + 63] = d63;
}

__global__ void wgmma_kernel_ss_tn_bf16_n256(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 256;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;
    float d32 = 0;
    float d33 = 0;
    float d34 = 0;
    float d35 = 0;
    float d36 = 0;
    float d37 = 0;
    float d38 = 0;
    float d39 = 0;
    float d40 = 0;
    float d41 = 0;
    float d42 = 0;
    float d43 = 0;
    float d44 = 0;
    float d45 = 0;
    float d46 = 0;
    float d47 = 0;
    float d48 = 0;
    float d49 = 0;
    float d50 = 0;
    float d51 = 0;
    float d52 = 0;
    float d53 = 0;
    float d54 = 0;
    float d55 = 0;
    float d56 = 0;
    float d57 = 0;
    float d58 = 0;
    float d59 = 0;
    float d60 = 0;
    float d61 = 0;
    float d62 = 0;
    float d63 = 0;
    float d64 = 0;
    float d65 = 0;
    float d66 = 0;
    float d67 = 0;
    float d68 = 0;
    float d69 = 0;
    float d70 = 0;
    float d71 = 0;
    float d72 = 0;
    float d73 = 0;
    float d74 = 0;
    float d75 = 0;
    float d76 = 0;
    float d77 = 0;
    float d78 = 0;
    float d79 = 0;
    float d80 = 0;
    float d81 = 0;
    float d82 = 0;
    float d83 = 0;
    float d84 = 0;
    float d85 = 0;
    float d86 = 0;
    float d87 = 0;
    float d88 = 0;
    float d89 = 0;
    float d90 = 0;
    float d91 = 0;
    float d92 = 0;
    float d93 = 0;
    float d94 = 0;
    float d95 = 0;
    float d96 = 0;
    float d97 = 0;
    float d98 = 0;
    float d99 = 0;
    float d100 = 0;
    float d101 = 0;
    float d102 = 0;
    float d103 = 0;
    float d104 = 0;
    float d105 = 0;
    float d106 = 0;
    float d107 = 0;
    float d108 = 0;
    float d109 = 0;
    float d110 = 0;
    float d111 = 0;
    float d112 = 0;
    float d113 = 0;
    float d114 = 0;
    float d115 = 0;
    float d116 = 0;
    float d117 = 0;
    float d118 = 0;
    float d119 = 0;
    float d120 = 0;
    float d121 = 0;
    float d122 = 0;
    float d123 = 0;
    float d124 = 0;
    float d125 = 0;
    float d126 = 0;
    float d127 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n256k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31,%32,%33,%34,%35,%36,%37,%38,%39,%40,%41,%42,%43,%44,%45,%46,%47,%48,%49,%50,%51,%52,%53,%54,%55,%56,%57,%58,%59,%60,%61,%62,%63,%64,%65,%66,%67,%68,%69,%70,%71,%72,%73,%74,%75,%76,%77,%78,%79,%80,%81,%82,%83,%84,%85,%86,%87,%88,%89,%90,%91,%92,%93,%94,%95,%96,%97,%98,%99,%100,%101,%102,%103,%104,%105,%106,%107,%108,%109,%110,%111,%112,%113,%114,%115,%116,%117,%118,%119,%120,%121,%122,%123,%124,%125,%126,%127}, %128, %129, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31), "+f"(d32), "+f"(d33), "+f"(d34), "+f"(d35), "+f"(d36), "+f"(d37), "+f"(d38), "+f"(d39), "+f"(d40), "+f"(d41), "+f"(d42), "+f"(d43), "+f"(d44), "+f"(d45), "+f"(d46), "+f"(d47), "+f"(d48), "+f"(d49), "+f"(d50), "+f"(d51), "+f"(d52), "+f"(d53), "+f"(d54), "+f"(d55), "+f"(d56), "+f"(d57), "+f"(d58), "+f"(d59), "+f"(d60), "+f"(d61), "+f"(d62), "+f"(d63), "+f"(d64), "+f"(d65), "+f"(d66), "+f"(d67), "+f"(d68), "+f"(d69), "+f"(d70), "+f"(d71), "+f"(d72), "+f"(d73), "+f"(d74), "+f"(d75), "+f"(d76), "+f"(d77), "+f"(d78), "+f"(d79), "+f"(d80), "+f"(d81), "+f"(d82), "+f"(d83), "+f"(d84), "+f"(d85), "+f"(d86), "+f"(d87), "+f"(d88), "+f"(d89), "+f"(d90), "+f"(d91), "+f"(d92), "+f"(d93), "+f"(d94), "+f"(d95), "+f"(d96), "+f"(d97), "+f"(d98), "+f"(d99), "+f"(d100), "+f"(d101), "+f"(d102), "+f"(d103), "+f"(d104), "+f"(d105), "+f"(d106), "+f"(d107), "+f"(d108), "+f"(d109), "+f"(d110), "+f"(d111), "+f"(d112), "+f"(d113), "+f"(d114), "+f"(d115), "+f"(d116), "+f"(d117), "+f"(d118), "+f"(d119), "+f"(d120), "+f"(d121), "+f"(d122), "+f"(d123), "+f"(d124), "+f"(d125), "+f"(d126), "+f"(d127)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 128 + 0] = d0;
    D[tid * 128 + 1] = d1;
    D[tid * 128 + 2] = d2;
    D[tid * 128 + 3] = d3;
    D[tid * 128 + 4] = d4;
    D[tid * 128 + 5] = d5;
    D[tid * 128 + 6] = d6;
    D[tid * 128 + 7] = d7;
    D[tid * 128 + 8] = d8;
    D[tid * 128 + 9] = d9;
    D[tid * 128 + 10] = d10;
    D[tid * 128 + 11] = d11;
    D[tid * 128 + 12] = d12;
    D[tid * 128 + 13] = d13;
    D[tid * 128 + 14] = d14;
    D[tid * 128 + 15] = d15;
    D[tid * 128 + 16] = d16;
    D[tid * 128 + 17] = d17;
    D[tid * 128 + 18] = d18;
    D[tid * 128 + 19] = d19;
    D[tid * 128 + 20] = d20;
    D[tid * 128 + 21] = d21;
    D[tid * 128 + 22] = d22;
    D[tid * 128 + 23] = d23;
    D[tid * 128 + 24] = d24;
    D[tid * 128 + 25] = d25;
    D[tid * 128 + 26] = d26;
    D[tid * 128 + 27] = d27;
    D[tid * 128 + 28] = d28;
    D[tid * 128 + 29] = d29;
    D[tid * 128 + 30] = d30;
    D[tid * 128 + 31] = d31;
    D[tid * 128 + 32] = d32;
    D[tid * 128 + 33] = d33;
    D[tid * 128 + 34] = d34;
    D[tid * 128 + 35] = d35;
    D[tid * 128 + 36] = d36;
    D[tid * 128 + 37] = d37;
    D[tid * 128 + 38] = d38;
    D[tid * 128 + 39] = d39;
    D[tid * 128 + 40] = d40;
    D[tid * 128 + 41] = d41;
    D[tid * 128 + 42] = d42;
    D[tid * 128 + 43] = d43;
    D[tid * 128 + 44] = d44;
    D[tid * 128 + 45] = d45;
    D[tid * 128 + 46] = d46;
    D[tid * 128 + 47] = d47;
    D[tid * 128 + 48] = d48;
    D[tid * 128 + 49] = d49;
    D[tid * 128 + 50] = d50;
    D[tid * 128 + 51] = d51;
    D[tid * 128 + 52] = d52;
    D[tid * 128 + 53] = d53;
    D[tid * 128 + 54] = d54;
    D[tid * 128 + 55] = d55;
    D[tid * 128 + 56] = d56;
    D[tid * 128 + 57] = d57;
    D[tid * 128 + 58] = d58;
    D[tid * 128 + 59] = d59;
    D[tid * 128 + 60] = d60;
    D[tid * 128 + 61] = d61;
    D[tid * 128 + 62] = d62;
    D[tid * 128 + 63] = d63;
    D[tid * 128 + 64] = d64;
    D[tid * 128 + 65] = d65;
    D[tid * 128 + 66] = d66;
    D[tid * 128 + 67] = d67;
    D[tid * 128 + 68] = d68;
    D[tid * 128 + 69] = d69;
    D[tid * 128 + 70] = d70;
    D[tid * 128 + 71] = d71;
    D[tid * 128 + 72] = d72;
    D[tid * 128 + 73] = d73;
    D[tid * 128 + 74] = d74;
    D[tid * 128 + 75] = d75;
    D[tid * 128 + 76] = d76;
    D[tid * 128 + 77] = d77;
    D[tid * 128 + 78] = d78;
    D[tid * 128 + 79] = d79;
    D[tid * 128 + 80] = d80;
    D[tid * 128 + 81] = d81;
    D[tid * 128 + 82] = d82;
    D[tid * 128 + 83] = d83;
    D[tid * 128 + 84] = d84;
    D[tid * 128 + 85] = d85;
    D[tid * 128 + 86] = d86;
    D[tid * 128 + 87] = d87;
    D[tid * 128 + 88] = d88;
    D[tid * 128 + 89] = d89;
    D[tid * 128 + 90] = d90;
    D[tid * 128 + 91] = d91;
    D[tid * 128 + 92] = d92;
    D[tid * 128 + 93] = d93;
    D[tid * 128 + 94] = d94;
    D[tid * 128 + 95] = d95;
    D[tid * 128 + 96] = d96;
    D[tid * 128 + 97] = d97;
    D[tid * 128 + 98] = d98;
    D[tid * 128 + 99] = d99;
    D[tid * 128 + 100] = d100;
    D[tid * 128 + 101] = d101;
    D[tid * 128 + 102] = d102;
    D[tid * 128 + 103] = d103;
    D[tid * 128 + 104] = d104;
    D[tid * 128 + 105] = d105;
    D[tid * 128 + 106] = d106;
    D[tid * 128 + 107] = d107;
    D[tid * 128 + 108] = d108;
    D[tid * 128 + 109] = d109;
    D[tid * 128 + 110] = d110;
    D[tid * 128 + 111] = d111;
    D[tid * 128 + 112] = d112;
    D[tid * 128 + 113] = d113;
    D[tid * 128 + 114] = d114;
    D[tid * 128 + 115] = d115;
    D[tid * 128 + 116] = d116;
    D[tid * 128 + 117] = d117;
    D[tid * 128 + 118] = d118;
    D[tid * 128 + 119] = d119;
    D[tid * 128 + 120] = d120;
    D[tid * 128 + 121] = d121;
    D[tid * 128 + 122] = d122;
    D[tid * 128 + 123] = d123;
    D[tid * 128 + 124] = d124;
    D[tid * 128 + 125] = d125;
    D[tid * 128 + 126] = d126;
    D[tid * 128 + 127] = d127;
}

__global__ void wgmma_kernel_ss_tn_fp16_n64(
    const __half* __restrict__ A,
    const __half* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __half* smem_a = reinterpret_cast<__half*>(smem);
    __half* smem_b = reinterpret_cast<__half*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k16.f32.f16.f16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, %32, %33, 1, 1, 1, 0, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

__global__ void wgmma_kernel_ss_tn_tf32_n64(
    const float* __restrict__ A,
    const float* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 8;
    constexpr int A_BYTES = M * K * 4;
    constexpr int B_BYTES = K * N * 4;

    extern __shared__ uint8_t smem[];
    float* smem_a = reinterpret_cast<float*>(smem);
    float* smem_b = reinterpret_cast<float*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k8.f32.tf32.tf32 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, %32, %33, 1, 1, 1;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

__global__ void wgmma_kernel_ss_tn_s8_n64(
    const int8_t* __restrict__ A,
    const int8_t* __restrict__ B,
    int32_t* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 32;
    constexpr int A_BYTES = M * K * 1;
    constexpr int B_BYTES = K * N * 1;

    extern __shared__ uint8_t smem[];
    int8_t* smem_a = reinterpret_cast<int8_t*>(smem);
    int8_t* smem_b = reinterpret_cast<int8_t*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    int32_t d0 = 0;
    int32_t d1 = 0;
    int32_t d2 = 0;
    int32_t d3 = 0;
    int32_t d4 = 0;
    int32_t d5 = 0;
    int32_t d6 = 0;
    int32_t d7 = 0;
    int32_t d8 = 0;
    int32_t d9 = 0;
    int32_t d10 = 0;
    int32_t d11 = 0;
    int32_t d12 = 0;
    int32_t d13 = 0;
    int32_t d14 = 0;
    int32_t d15 = 0;
    int32_t d16 = 0;
    int32_t d17 = 0;
    int32_t d18 = 0;
    int32_t d19 = 0;
    int32_t d20 = 0;
    int32_t d21 = 0;
    int32_t d22 = 0;
    int32_t d23 = 0;
    int32_t d24 = 0;
    int32_t d25 = 0;
    int32_t d26 = 0;
    int32_t d27 = 0;
    int32_t d28 = 0;
    int32_t d29 = 0;
    int32_t d30 = 0;
    int32_t d31 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k32.s32.s8.s8 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, %32, %33, 1;\n"
            : "+r"(d0), "+r"(d1), "+r"(d2), "+r"(d3), "+r"(d4), "+r"(d5), "+r"(d6), "+r"(d7), "+r"(d8), "+r"(d9), "+r"(d10), "+r"(d11), "+r"(d12), "+r"(d13), "+r"(d14), "+r"(d15), "+r"(d16), "+r"(d17), "+r"(d18), "+r"(d19), "+r"(d20), "+r"(d21), "+r"(d22), "+r"(d23), "+r"(d24), "+r"(d25), "+r"(d26), "+r"(d27), "+r"(d28), "+r"(d29), "+r"(d30), "+r"(d31)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

__global__ void wgmma_kernel_ss_nt_bf16_n64(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;

    uint64_t descA = make_smem_desc(smem_a, /*ld=*/256, /*sd=*/16, 0);
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, %32, %33, 1, 1, 1, 1, 1;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31)
            : "l"(descA), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

__global__ void wgmma_kernel_rs_tn_bf16_n64(
    const __nv_bfloat16* __restrict__ A,
    const __nv_bfloat16* __restrict__ B,
    float* __restrict__ D)
{
    constexpr int M = 64;
    constexpr int N = 64;
    constexpr int K = 16;
    constexpr int A_BYTES = M * K * 2;
    constexpr int B_BYTES = K * N * 2;

    extern __shared__ uint8_t smem[];
    __nv_bfloat16* smem_a = reinterpret_cast<__nv_bfloat16*>(smem);
    __nv_bfloat16* smem_b = reinterpret_cast<__nv_bfloat16*>(smem + A_BYTES);

    int tid = threadIdx.x;

    // Cooperative load of A (M*K elements) and B (K*N elements) from gmem.
    for (int i = tid; i < M * K; i += 128) smem_a[i] = A[i];
    for (int i = tid; i < K * N; i += 128) smem_b[i] = B[i];
    __syncthreads();

    float d0 = 0;
    float d1 = 0;
    float d2 = 0;
    float d3 = 0;
    float d4 = 0;
    float d5 = 0;
    float d6 = 0;
    float d7 = 0;
    float d8 = 0;
    float d9 = 0;
    float d10 = 0;
    float d11 = 0;
    float d12 = 0;
    float d13 = 0;
    float d14 = 0;
    float d15 = 0;
    float d16 = 0;
    float d17 = 0;
    float d18 = 0;
    float d19 = 0;
    float d20 = 0;
    float d21 = 0;
    float d22 = 0;
    float d23 = 0;
    float d24 = 0;
    float d25 = 0;
    float d26 = 0;
    float d27 = 0;
    float d28 = 0;
    float d29 = 0;
    float d30 = 0;
    float d31 = 0;

    // Build descB (B in shared) and A register vector (A in registers).
    uint64_t descB = make_smem_desc(smem_b, /*ld=*/256, /*sd=*/16, 0);
    const uint32_t* a_pack = reinterpret_cast<const uint32_t*>(smem_a);
    uint32_t a_reg0 = a_pack[(tid * 4) + 0];
    uint32_t a_reg1 = a_pack[(tid * 4) + 1];
    uint32_t a_reg2 = a_pack[(tid * 4) + 2];
    uint32_t a_reg3 = a_pack[(tid * 4) + 3];

    constexpr int N_INNER = 1024;   // serialized wgmma issues per launch (accumulator-chained)

    asm volatile("wgmma.fence.sync.aligned;\n");
    #pragma unroll 1
    for (int it = 0; it < N_INNER; ++it) {
        asm volatile(
            "wgmma.mma_async.sync.aligned.m64n64k16.f32.bf16.bf16 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31}, {%32,%33,%34,%35}, %36, 1, 1, 1, 0;\n"
            : "+f"(d0), "+f"(d1), "+f"(d2), "+f"(d3), "+f"(d4), "+f"(d5), "+f"(d6), "+f"(d7), "+f"(d8), "+f"(d9), "+f"(d10), "+f"(d11), "+f"(d12), "+f"(d13), "+f"(d14), "+f"(d15), "+f"(d16), "+f"(d17), "+f"(d18), "+f"(d19), "+f"(d20), "+f"(d21), "+f"(d22), "+f"(d23), "+f"(d24), "+f"(d25), "+f"(d26), "+f"(d27), "+f"(d28), "+f"(d29), "+f"(d30), "+f"(d31)
            : "r"(a_reg0), "r"(a_reg1), "r"(a_reg2), "r"(a_reg3), "l"(descB));
    }
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned 0;\n");

    D[tid * 32 + 0] = d0;
    D[tid * 32 + 1] = d1;
    D[tid * 32 + 2] = d2;
    D[tid * 32 + 3] = d3;
    D[tid * 32 + 4] = d4;
    D[tid * 32 + 5] = d5;
    D[tid * 32 + 6] = d6;
    D[tid * 32 + 7] = d7;
    D[tid * 32 + 8] = d8;
    D[tid * 32 + 9] = d9;
    D[tid * 32 + 10] = d10;
    D[tid * 32 + 11] = d11;
    D[tid * 32 + 12] = d12;
    D[tid * 32 + 13] = d13;
    D[tid * 32 + 14] = d14;
    D[tid * 32 + 15] = d15;
    D[tid * 32 + 16] = d16;
    D[tid * 32 + 17] = d17;
    D[tid * 32 + 18] = d18;
    D[tid * 32 + 19] = d19;
    D[tid * 32 + 20] = d20;
    D[tid * 32 + 21] = d21;
    D[tid * 32 + 22] = d22;
    D[tid * 32 + 23] = d23;
    D[tid * 32 + 24] = d24;
    D[tid * 32 + 25] = d25;
    D[tid * 32 + 26] = d26;
    D[tid * 32 + 27] = d27;
    D[tid * 32 + 28] = d28;
    D[tid * 32 + 29] = d29;
    D[tid * 32 + 30] = d30;
    D[tid * 32 + 31] = d31;
}

template <typename A_T, typename D_T>
void run_config(
    const char* name, int M, int N, int K,
    size_t a_bytes, size_t b_bytes, size_t d_bytes, size_t smem_bytes,
    void (*kernel)(const A_T*, const A_T*, D_T*),
    int warmup, int timed)
{
    A_T *dA, *dB; D_T *dD;
    CUDA_CHECK(cudaMalloc(&dA, a_bytes));
    CUDA_CHECK(cudaMalloc(&dB, b_bytes));
    CUDA_CHECK(cudaMalloc(&dD, d_bytes));

    // Fill A, B with one-valued elements (per dtype). Expected D[i,j] = K.
    int n_a = a_bytes / sizeof(A_T);
    int n_b = b_bytes / sizeof(A_T);
    A_T* hA = new A_T[n_a];
    A_T* hB = new A_T[n_b];
    for (int i = 0; i < n_a; ++i) {
        if constexpr (std::is_same_v<A_T, __nv_bfloat16>) hA[i] = __float2bfloat16(1.0f);
        else if constexpr (std::is_same_v<A_T, __half>)   hA[i] = __float2half(1.0f);
        else if constexpr (std::is_same_v<A_T, float>)    hA[i] = 1.0f;
        else hA[i] = (A_T)1;
    }
    for (int i = 0; i < n_b; ++i) {
        if constexpr (std::is_same_v<A_T, __nv_bfloat16>) hB[i] = __float2bfloat16(1.0f);
        else if constexpr (std::is_same_v<A_T, __half>)   hB[i] = __float2half(1.0f);
        else if constexpr (std::is_same_v<A_T, float>)    hB[i] = 1.0f;
        else hB[i] = (A_T)1;
    }
    CUDA_CHECK(cudaMemcpy(dA, hA, a_bytes, cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(dB, hB, b_bytes, cudaMemcpyHostToDevice));

    cudaFuncSetAttribute((const void*)kernel,
                         cudaFuncAttributeMaxDynamicSharedMemorySize,
                         int(smem_bytes));

    // Warmup.
    for (int i = 0; i < warmup; ++i) {
        CUDA_CHECK(cudaMemset(dD, 0, d_bytes));
        kernel<<<1, 128, smem_bytes>>>(dA, dB, dD);
    }
    CUDA_CHECK(cudaDeviceSynchronize());

    // Timed.
    cudaEvent_t e0, e1;
    cudaEventCreate(&e0); cudaEventCreate(&e1);
    std::vector<float> ms;
    ms.reserve(timed);
    for (int i = 0; i < timed; ++i) {
        cudaEventRecord(e0);
        kernel<<<1, 128, smem_bytes>>>(dA, dB, dD);
        cudaEventRecord(e1);
        cudaEventSynchronize(e1);
        float t = 0;
        cudaEventElapsedTime(&t, e0, e1);
        ms.push_back(t);
    }
    cudaEventDestroy(e0); cudaEventDestroy(e1);
    std::sort(ms.begin(), ms.end());
    float median_ms = ms[ms.size() / 2];

    // The kernel issues N_INNER serialized wgmma per launch (accumulator-chained),
    // so each output cell ends at K * N_INNER. The constant must mirror gen_wgmma_zoo.py.
    constexpr int N_INNER = 1024;
    int expected = K * N_INNER;

    int n_d = d_bytes / sizeof(D_T);
    D_T* hD = new D_T[n_d];
    CUDA_CHECK(cudaMemcpy(hD, dD, d_bytes, cudaMemcpyDeviceToHost));
    int matched = 0, written = 0;
    for (int i = 0; i < n_d; ++i) {
        if (hD[i] != (D_T)0) ++written;
        if (hD[i] == (D_T)expected) ++matched;
    }

    // FLOPs across all serialized wgmma issuances per launch:
    //   N_INNER * 2 * M * N * K  (each wgmma issues M*N MAC = 2*M*N*K FLOPs).
    double flops = double(N_INNER) * 2.0 * M * N * K;
    double tflops = flops / (median_ms * 1e-3) / 1e12;

    printf("%s,%d,%d,%d,%zu,%.5f,%d,%d,%d,%.3f\n",
           name, M, N, K, smem_bytes, median_ms, written, matched, n_d, tflops);

    delete[] hA; delete[] hB; delete[] hD;
    cudaFree(dA); cudaFree(dB); cudaFree(dD);
}

int main() {
    int warmup = 5, timed = 20;
    printf("config,M,N,K,smem_bytes,median_ms,written,matched,total,tflops\n");


    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n8", 64, 8, 16,
        2048, 256, 2048, 2304,
        wgmma_kernel_ss_tn_bf16_n8,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n16", 64, 16, 16,
        2048, 512, 4096, 2560,
        wgmma_kernel_ss_tn_bf16_n16,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n32", 64, 32, 16,
        2048, 1024, 8192, 3072,
        wgmma_kernel_ss_tn_bf16_n32,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n64", 64, 64, 16,
        2048, 2048, 16384, 4096,
        wgmma_kernel_ss_tn_bf16_n64,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n128", 64, 128, 16,
        2048, 4096, 32768, 6144,
        wgmma_kernel_ss_tn_bf16_n128,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_tn_bf16_n256", 64, 256, 16,
        2048, 8192, 65536, 10240,
        wgmma_kernel_ss_tn_bf16_n256,
        warmup, timed);

    run_config<__half, float>(
        "ss_tn_fp16_n64", 64, 64, 16,
        2048, 2048, 16384, 4096,
        wgmma_kernel_ss_tn_fp16_n64,
        warmup, timed);

    run_config<float, float>(
        "ss_tn_tf32_n64", 64, 64, 8,
        2048, 2048, 16384, 4096,
        wgmma_kernel_ss_tn_tf32_n64,
        warmup, timed);

    run_config<int8_t, int32_t>(
        "ss_tn_s8_n64", 64, 64, 32,
        2048, 2048, 16384, 4096,
        wgmma_kernel_ss_tn_s8_n64,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "ss_nt_bf16_n64", 64, 64, 16,
        2048, 2048, 16384, 4096,
        wgmma_kernel_ss_nt_bf16_n64,
        warmup, timed);

    run_config<__nv_bfloat16, float>(
        "rs_tn_bf16_n64", 64, 64, 16,
        2048, 2048, 16384, 4096,
        wgmma_kernel_rs_tn_bf16_n64,
        warmup, timed);
    return 0;
}

